# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/MAC_AXIS_ILA/MAC_AXIS_ILA.xci
# IP: The module: 'MAC_AXIS_ILA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/MAC_AXIS_ILA/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'MAC_AXIS_ILA'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/MAC_AXIS_ILA/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'MAC_AXIS_ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/MAC_AXIS_ILA/MAC_AXIS_ILA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MAC_AXIS_ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/MAC_AXIS_ILA/MAC_AXIS_ILA.xci
# IP: The module: 'MAC_AXIS_ILA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/MAC_AXIS_ILA/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'MAC_AXIS_ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/MAC_AXIS_ILA/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'MAC_AXIS_ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/MAC_AXIS_ILA/MAC_AXIS_ILA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MAC_AXIS_ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
