# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/xdc/m_top.xdc

# IP: C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/vio_0/vio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# Block Designs: C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_management/system_management.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_management || ORIG_REF_NAME==system_management} -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_management/ip/system_management_sys_man_wiz_0/system_management_sys_man_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_management_sys_man_wiz_0 || ORIG_REF_NAME==system_management_sys_man_wiz_0} -quiet] -quiet

# Block Designs: C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/system_interconnect.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_interconnect || ORIG_REF_NAME==system_interconnect} -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_xbar_0/system_interconnect_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_interconnect_xbar_0 || ORIG_REF_NAME==system_interconnect_xbar_0} -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_6/system_interconnect_auto_cc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_interconnect_auto_cc_6 || ORIG_REF_NAME==system_interconnect_auto_cc_6} -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_0/system_interconnect_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_interconnect_auto_cc_0 || ORIG_REF_NAME==system_interconnect_auto_cc_0} -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_1/system_interconnect_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_interconnect_auto_cc_1 || ORIG_REF_NAME==system_interconnect_auto_cc_1} -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_2/system_interconnect_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_interconnect_auto_cc_2 || ORIG_REF_NAME==system_interconnect_auto_cc_2} -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_3/system_interconnect_auto_cc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_interconnect_auto_cc_3 || ORIG_REF_NAME==system_interconnect_auto_cc_3} -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_4/system_interconnect_auto_cc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_interconnect_auto_cc_4 || ORIG_REF_NAME==system_interconnect_auto_cc_4} -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_5/system_interconnect_auto_cc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_interconnect_auto_cc_5 || ORIG_REF_NAME==system_interconnect_auto_cc_5} -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_axi_interconnect_0/system_interconnect_axi_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_interconnect_axi_interconnect_0 || ORIG_REF_NAME==system_interconnect_axi_interconnect_0} -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_management/system_management_ooc.xdc

# XDC: c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/system_interconnect_ooc.xdc
