# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/eorzes/cernbox/git/zynq_rec_fiber/prj/m_top/m_top.runs/synth_1/m_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/eorzes/cernbox/git/zynq_rec_fiber/prj/m_top/m_top.cache/wt [current_project]
set_property parent.project_path C:/Users/eorzes/cernbox/git/zynq_rec_fiber/prj/m_top/m_top.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zcu102:part0:3.4 [current_project]
set_property ip_output_repo c:/Users/eorzes/cernbox/git/zynq_rec_fiber/prj/m_top/m_top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/enc8b10b/asic_encode_8b10b.v
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/prj/m_gth_ex/imports/gtwizard_ultrascale_v1_7_gthe4_common.v
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/gt/m_gt_qpll.v
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/prj/m_gth_ex/imports/m_gth_gthe4_common_wrapper.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/AXI_lane_pkg.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/clock_monitor_full.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/UDP_bridge/MAC_PCS_PMA.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/UDP_bridge/UDP_Packet_RX.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/UDP_bridge/UDP_Packet_TX.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/UDP_bridge/axis_to_axi.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/bit_synch.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/bus_synch.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/UDP_bridge/bus_synchronizer.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/cdc_bit.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/cdc_vec.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/reset_sync.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/freq_meas.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/hb.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/clk_buf.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/datagen_check/data_generator.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/gt/gt_buf.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/tclink_phase_detector/dmtd_phase_meas.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/tclink_phase_detector/ddmtd_wrap.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/divide6.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/tclink_phase_detector/dmtd_with_deglitcher.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/tclink_phase_detector/gc_extend_pulse.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/tclink_phase_detector/gc_pulse_synchronizer.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/tclink_phase_detector/gc_sync_ffs.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/synchronizer.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/hysteresis_monostable.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/enc8b10b/multibyte_enc8b10b.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/oddr.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/oddr40.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/hdl/system_interconnect_wrapper.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_management/hdl/system_management_wrapper.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/UDP_bridge/udp_bridge.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/gt/gt_pkg.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/sys_ctrl/system_control.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/UDP_bridge/AXI_interface.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/datagen_check/data_checker.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/aligner/fsm_aligner.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/utils/utility_pkg.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/gt/m_gt.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/sys_man/sys_man_wrap.vhd
  C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/hdl/m_top.vhd
}
read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/vio_0/vio_0.xci
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/vio_0/vio_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/vio_0/vio_0_ooc.xdc]

add_files C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_management/system_management.bd
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_management/ip/system_management_sys_man_wiz_0/system_management_sys_man_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_management/ip/system_management_sys_man_wiz_0/system_management_sys_man_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_management/ip/system_management_sys_man_wiz_0/system_management_sys_man_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_management/system_management_ooc.xdc]

add_files C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/system_interconnect.bd
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_xbar_0/system_interconnect_xbar_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_6/system_interconnect_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_6/system_interconnect_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_6/system_interconnect_auto_cc_6_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_0/system_interconnect_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_0/system_interconnect_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_0/system_interconnect_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_1/system_interconnect_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_1/system_interconnect_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_1/system_interconnect_auto_cc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_2/system_interconnect_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_2/system_interconnect_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_2/system_interconnect_auto_cc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_3/system_interconnect_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_3/system_interconnect_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_3/system_interconnect_auto_cc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_4/system_interconnect_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_4/system_interconnect_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_4/system_interconnect_auto_cc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_5/system_interconnect_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_5/system_interconnect_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/ip/system_interconnect_auto_cc_5/system_interconnect_auto_cc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/bd/system_interconnect/system_interconnect_ooc.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/MAC_AXIS_ILA/MAC_AXIS_ILA.xci
set_property used_in_synthesis false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/MAC_AXIS_ILA/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/MAC_AXIS_ILA/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/MAC_AXIS_ILA/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/MAC_AXIS_ILA/MAC_AXIS_ILA_ooc.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/m_gth/m_gth.xci
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/m_gth/synth/m_gth_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/m_gth/synth/m_gth.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/vio_sys/vio_2.xci
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/vio_sys/vio_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/vio_sys/vio_2_ooc.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5.xci
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5_late.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5_ooc.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_sys/ila_sys.xci
set_property used_in_synthesis false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_sys/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_sys/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_sys/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_sys/ila_sys_ooc.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/AXI_I2C/AXI_I2C.xci
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/AXI_I2C/AXI_I2C_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/AXI_I2C/AXI_I2C_ooc.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/PCS_PMA/PCS_PMA.xci
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/PCS_PMA/ip_0/synth/PCS_PMA_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/PCS_PMA/ip_0/synth/PCS_PMA_gt.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/PCS_PMA/PCS_PMA_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/PCS_PMA/synth/PCS_PMA.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/PCS_PMA/synth/PCS_PMA_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/PCS_PMA/synth/PCS_PMA_ooc.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_1/ila_1.xci
set_property used_in_synthesis false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_1/ila_1_ooc.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/gearbox_1_to_4/gearbox_1_to_4.xci
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/gearbox_1_to_4/gearbox_1_to_4_ooc.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/vio_1/vio_1.xci
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/vio_1/vio_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/vio_1/vio_1_ooc.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/Ethernet_Setup_VIO/Ethernet_Setup_VIO.xci
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/Ethernet_Setup_VIO/Ethernet_Setup_VIO.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/Ethernet_Setup_VIO/Ethernet_Setup_VIO_ooc.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/gearbox_4_to_1/gearbox_4_to_1.xci
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/gearbox_4_to_1/gearbox_4_to_1_ooc.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/UDP_bridge_CDC_FIFO/UDP_bridge_CDC_FIFO.xci
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/UDP_bridge_CDC_FIFO/UDP_bridge_CDC_FIFO_ooc.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/axi_gpio/axi_gpio_0.xci
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/axi_gpio/axi_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/axi_gpio/axi_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/axi_gpio/axi_gpio_0.xdc]

read_ip -quiet C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/MAC/MAC.xci
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/MAC/synth/MAC_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/MAC/synth/MAC.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/MAC/synth/MAC_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/ip/udp_bridge/MAC/synth/MAC_clocks.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/xdc/m_top.xdc
set_property used_in_implementation false [get_files C:/Users/eorzes/cernbox/git/zynq_rec_fiber/src/xdc/m_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top m_top -part xczu9eg-ffvb1156-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef m_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file m_top_utilization_synth.rpt -pb m_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
