# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/eorzes/cernbox/git/fanout_sma/src/bd/system_interconnect/ip/system_interconnect_auto_cc_3/system_interconnect_auto_cc_3.xci
# IP: The module: 'system_interconnect_auto_cc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/bd/system_interconnect/ip/system_interconnect_auto_cc_3/system_interconnect_auto_cc_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_interconnect_auto_cc_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/bd/system_interconnect/ip/system_interconnect_auto_cc_3/system_interconnect_auto_cc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_interconnect_auto_cc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/eorzes/cernbox/git/fanout_sma/src/bd/system_interconnect/ip/system_interconnect_auto_cc_3/system_interconnect_auto_cc_3.xci
# IP: The module: 'system_interconnect_auto_cc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/bd/system_interconnect/ip/system_interconnect_auto_cc_3/system_interconnect_auto_cc_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_interconnect_auto_cc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/bd/system_interconnect/ip/system_interconnect_auto_cc_3/system_interconnect_auto_cc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_interconnect_auto_cc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
