# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/PCS_PMA.xci
# IP: The module: 'PCS_PMA' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/ip_0/PCS_PMA_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCS_PMA_gt || ORIG_REF_NAME==PCS_PMA_gt} -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/ip_0/synth/PCS_PMA_gt_ooc.xdc

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/ip_0/synth/PCS_PMA_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCS_PMA_gt || ORIG_REF_NAME==PCS_PMA_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/PCS_PMA_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCS_PMA'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/synth/PCS_PMA.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCS_PMA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/synth/PCS_PMA_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCS_PMA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/synth/PCS_PMA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCS_PMA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/PCS_PMA.xci
# IP: The module: 'PCS_PMA' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/ip_0/PCS_PMA_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCS_PMA_gt || ORIG_REF_NAME==PCS_PMA_gt} -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/ip_0/synth/PCS_PMA_gt_ooc.xdc

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/ip_0/synth/PCS_PMA_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PCS_PMA_gt || ORIG_REF_NAME==PCS_PMA_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/PCS_PMA_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCS_PMA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/synth/PCS_PMA.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCS_PMA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/synth/PCS_PMA_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCS_PMA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/PCS_PMA/synth/PCS_PMA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCS_PMA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
