# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/eorzes/cernbox/git/fanout_sma/src/ip/ila_sys/ila_sys.xci
# IP: The module: 'ila_sys' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/ila_sys/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_sys'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/ila_sys/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/ila_sys/ila_sys_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/fanout_sma/src/ip/ila_sys/ila_sys.xci
# IP: The module: 'ila_sys' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/ila_sys/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/ila_sys/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/ila_sys/ila_sys_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
