# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/UDP_bridge_CDC_FIFO/UDP_bridge_CDC_FIFO.xci
# IP: The module: 'UDP_bridge_CDC_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/UDP_bridge_CDC_FIFO/UDP_bridge_CDC_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UDP_bridge_CDC_FIFO'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/UDP_bridge_CDC_FIFO/UDP_bridge_CDC_FIFO.xci
# IP: The module: 'UDP_bridge_CDC_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/UDP_bridge_CDC_FIFO/UDP_bridge_CDC_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UDP_bridge_CDC_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
