# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5.xci
# IP: The module: 'clk_pcs_pma_62_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pcs_pma_62_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pcs_pma_62_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pcs_pma_62_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pcs_pma_62_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5.xci
# IP: The module: 'clk_pcs_pma_62_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pcs_pma_62_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pcs_pma_62_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pcs_pma_62_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/clk_pcs_pma_62_5/clk_pcs_pma_62_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pcs_pma_62_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
