# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/gearbox_4_to_1/gearbox_4_to_1.xci
# IP: The module: 'gearbox_4_to_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/gearbox_4_to_1/gearbox_4_to_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gearbox_4_to_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/gearbox_4_to_1/gearbox_4_to_1.xci
# IP: The module: 'gearbox_4_to_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eorzes/cernbox/git/fanout_sma/src/ip/udp_bridge/gearbox_4_to_1/gearbox_4_to_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gearbox_4_to_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
